# Default variables specific to the samples in the DotnetSnes repository
ARTIFACTS_ROOT ?= $(abspath bin/Release/net8.0)
DNSNES_CORE_DIR ?= $(abspath ../DotnetSnes.Core)
DNTC_TOOL_CSPROJ ?= $(abspath ../../../DntcTranspiler/Dntc.Cli/Dntc.Cli.csproj)
DNSNES_BASE_MAKEFILE ?= $(abspath ../Makefile.base)
