#!/bin/bash

if [ "$SUDO_USER" ]; then

    USER_HOME=$(eval echo "~$SUDO_USER")

else

    USER_HOME="$HOME"

fi

# Check if wine is installed
if ! command -v wine &> /dev/null; then

    echo "Wine is not installed. Please install wine first."
    exit 1
    
fi

# Check if wine is configured
if [ ! -d "$USER_HOME/.wine" ]; then

    echo "Wine is not configured. Initializing wine prefix..."
    wineboot --init

fi

export WINEPREFIX="$USER_HOME/.wine-snes-ide"

if [ ! -d "$WINEPREFIX" ]; then

    echo "Creating wine prefix for snes-ide..."
    wineboot --init
    
fi

SRC_DIR="$(dirname "$(realpath "$0")")"

cd "$SRC_DIR"

PYTHON_INSTALLER="$(find ../installers/python -type f -name '*' | head -n 1)"

# Check and run Python installer
if [ -f "$PYTHON_INSTALLER" ]; then

    echo "Running Python installer in wine..."
    wine "$PYTHON_INSTALLER"

else

    echo "Python installer ($PYTHON_INSTALLER) not found."

fi

# Run install.sh in current directory
if [ -f "./install.sh" ]; then

    echo "Running install.sh..."
    bash ./install.sh

else

    echo "install.sh not found in current directory."

fi
